name: Hoodbot Research Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_enhanced.txt

    - name: Run system diagnostics
      run: python test_enhanced_system.py

    - name: Validate SQLite database
      run: |
        python -c "import sqlite3; conn = sqlite3.connect('enhanced_arielle.db'); print('DB Connected:', conn.total_changes == 0)"

    - name: Log model configuration
      run: |
        echo "Claude config:" && type config\\claude_config.json
        echo "OpenAI config:" && type config\\openai_config.json

    - name: Archive logs
      uses: actions/upload-artifact@v3
      with:
        name: hoodbot-logs
        path: logs/
